name: Build RPM Package

on:
  workflow_run:
    workflows: ["Weekly Docker RISC-V64 Build", "Track Moby Releases"]
    types: [completed]
    branches: [main]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to build package from'
        required: true
        default: 'v28.5.1-riscv64'

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if new release exists
        id: check_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail

          # Skip check for manual dispatch
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Manual dispatch - proceeding with build"
            echo "has_new_release=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Find the latest docker release using JSON output
          RELEASE_TAG=$(gh release list --repo gounthar/docker-for-riscv64 --limit 50 --json tagName | \
                        jq -r '.[] | select(.tagName | test("^v[0-9]+\\.[0-9]+\\.[0-9]+-riscv64$")) | .tagName' | \
                        head -1)

          if [ -z "$RELEASE_TAG" ]; then
            echo "No Docker release found - skipping package build"
            echo "has_new_release=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Check if release already has .rpm packages
          ASSETS=$(gh release view "$RELEASE_TAG" --json assets --jq '.assets[].name' 2>/dev/null || echo "")
          if echo "$ASSETS" | grep -q 'moby-engine.*\.rpm$'; then
            echo "Release $RELEASE_TAG already has RPM packages - skipping build"
            echo "has_new_release=false" >> $GITHUB_OUTPUT
          else
            echo "Release $RELEASE_TAG needs RPM packages - proceeding with build"
            echo "has_new_release=true" >> $GITHUB_OUTPUT
          fi

      - name: Install build dependencies
        if: steps.check_release.outputs.has_new_release == 'true'
        run: |
          # Check if running on Fedora or Debian
          if [ -f /etc/fedora-release ]; then
            sudo dnf install -y rpm-build rpmdevtools rpmlint createrepo_c
          elif [ -f /etc/debian_version ]; then
            sudo apt-get update
            sudo apt-get install -y rpm rpmlint createrepo-c
          else
            echo "Unsupported distribution"
            exit 1
          fi

      - name: Set up RPM build tree
        if: steps.check_release.outputs.has_new_release == 'true'
        run: |
          rpmdev-setuptree || mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

      - name: Download release binaries
        if: steps.check_release.outputs.has_new_release == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail

          # Get release tag from workflow_run or manual input
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            RELEASE_TAG="${{ github.event.inputs.release_tag }}"
          else
            # Find the latest docker release created by the workflow using JSON output
            RELEASE_TAG=$(gh release list --repo gounthar/docker-for-riscv64 --limit 50 --json tagName | \
                          jq -r '.[] | select(.tagName | test("^v[0-9]+\\.[0-9]+\\.[0-9]+-riscv64$")) | .tagName' | \
                          head -1)
          fi

          # Validate RELEASE_TAG is not empty
          if [ -z "$RELEASE_TAG" ]; then
            echo "Error: No matching release found"
            exit 1
          fi

          echo "Building package for release: $RELEASE_TAG"
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

          # Clean and download all binaries to SOURCES directory
          cd ~/rpmbuild/SOURCES
          rm -f dockerd docker-proxy containerd containerd-shim-runc-v2 runc
          for binary in dockerd docker-proxy containerd containerd-shim-runc-v2 runc; do
            gh release download $RELEASE_TAG -p $binary --repo gounthar/docker-for-riscv64
            if [ ! -f "$binary" ]; then
              echo "Error: Failed to download $binary from release $RELEASE_TAG"
              exit 1
            fi
          done

          chmod +x *
          ls -lh

      - name: Copy spec files and sources
        if: steps.check_release.outputs.has_new_release == 'true'
        run: |
          # Copy systemd unit files to SOURCES
          cp rpm-docker/docker.service ~/rpmbuild/SOURCES/
          cp rpm-docker/docker.socket ~/rpmbuild/SOURCES/
          cp rpm-containerd/containerd.service ~/rpmbuild/SOURCES/

          # Copy spec files to SPECS
          cp rpm-docker/moby-engine.spec ~/rpmbuild/SPECS/
          cp rpm-containerd/containerd.spec ~/rpmbuild/SPECS/
          cp rpm-runc/runc.spec ~/rpmbuild/SPECS/

      - name: Update package versions
        if: steps.check_release.outputs.has_new_release == 'true'
        run: |
          # Extract version from tag (v28.5.1-riscv64 -> 28.5.1)
          VERSION=$(echo $RELEASE_TAG | sed 's/^v//; s/-riscv64$//')
          echo "Package version: $VERSION"

          # Update moby-engine version
          sed -i "s/^Version:.*/Version:        $VERSION/" ~/rpmbuild/SPECS/moby-engine.spec

      - name: Build RPM packages
        if: steps.check_release.outputs.has_new_release == 'true'
        run: |
          # Build each package
          cd ~/rpmbuild/SPECS

          echo "Building runc..."
          rpmbuild -bb --target riscv64 runc.spec

          echo "Building containerd..."
          rpmbuild -bb --target riscv64 containerd.spec

          echo "Building moby-engine..."
          rpmbuild -bb --target riscv64 moby-engine.spec

          # List built packages
          echo ""
          echo "Built RPM packages:"
          ls -lh ~/rpmbuild/RPMS/riscv64/

      - name: Run rpmlint checks
        if: steps.check_release.outputs.has_new_release == 'true'
        run: |
          rpmlint ~/rpmbuild/RPMS/riscv64/*.rpm || true

      - name: Package info
        if: steps.check_release.outputs.has_new_release == 'true'
        run: |
          for rpm in ~/rpmbuild/RPMS/riscv64/*.rpm; do
            echo "============================================"
            echo "=== Package: $(basename $rpm) ==="
            echo "============================================"
            echo ""
            echo "=== Package Info ==="
            rpm -qip "$rpm"
            echo ""
            echo "=== Package Contents ==="
            rpm -qlp "$rpm"
            echo ""
            echo "=== Package Size ==="
            ls -lh "$rpm"
            echo ""
          done

      - name: Import GPG signing key
        if: steps.check_release.outputs.has_new_release == 'true'
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          set -euo pipefail
          echo "Importing GPG key for package signing..."
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import

          # Verify key imported
          echo ""
          echo "GPG keys available:"
          gpg --list-secret-keys
          echo ""
          echo "GPG key imported successfully"

      - name: Sign RPM packages
        if: steps.check_release.outputs.has_new_release == 'true'
        run: |
          set -euo pipefail
          echo "Signing RPM packages..."

          # Install rpm-sign if needed
          if ! command -v rpmsign >/dev/null 2>&1; then
            if [ -f /etc/fedora-release ]; then
              sudo dnf install -y rpm-sign
            elif [ -f /etc/debian_version ]; then
              sudo apt-get update && sudo apt-get install -y rpm
            fi
          fi

          # Get GPG key ID
          GPG_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG --with-colons | awk -F: '/^sec:/ {print $5; exit}')
          echo "Using GPG key ID: $GPG_KEY_ID"

          # Sign each RPM package
          for rpm in ~/rpmbuild/RPMS/riscv64/*.rpm; do
            echo "Signing $(basename $rpm)..."
            setsid rpmsign --addsign --define "_gpg_name $GPG_KEY_ID" "$rpm" || { echo "Error: Failed to sign $rpm"; exit 1; }
          done

          echo ""
          echo "✅ All packages signed successfully"
          echo ""

          # Verify signatures
          echo "Verifying signatures:"
          for rpm in ~/rpmbuild/RPMS/riscv64/*.rpm; do
            echo "Checking $(basename $rpm)..."
            rpm -qip "$rpm" | grep -i signature || echo "Warning: No signature found"
          done

      - name: Upload packages to release
        if: steps.check_release.outputs.has_new_release == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Uploading packages to release $RELEASE_TAG"
          echo ""

          for rpm in ~/rpmbuild/RPMS/riscv64/*.rpm; do
            echo "Uploading $(basename $rpm)..."
            gh release upload $RELEASE_TAG "$rpm" --repo gounthar/docker-for-riscv64 --clobber
          done

          echo ""
          echo "✅ All RPM packages uploaded successfully!"
          echo ""
          echo "Packages built:"
          ls -lh ~/rpmbuild/RPMS/riscv64/
          echo ""
          echo "Install with:"
          echo "  # Download all packages"
          echo "  wget https://github.com/gounthar/docker-for-riscv64/releases/download/${RELEASE_TAG}/runc-*.riscv64.rpm"
          echo "  wget https://github.com/gounthar/docker-for-riscv64/releases/download/${RELEASE_TAG}/containerd-*.riscv64.rpm"
          echo "  wget https://github.com/gounthar/docker-for-riscv64/releases/download/${RELEASE_TAG}/moby-engine-*.riscv64.rpm"
          echo ""
          echo "  # Install in dependency order"
          echo "  sudo dnf install -y runc-*.riscv64.rpm"
          echo "  sudo dnf install -y containerd-*.riscv64.rpm"
          echo "  sudo dnf install -y moby-engine-*.riscv64.rpm"
